[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "grammars"
version = "0.1"
requires-python = ">= 3.12"
description = "gnml, tkml - using parsimonious"
